apiVersion: v1
kind: List
metadata:
items:
#zk
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: zk
    name: zk
  spec:
    podManagementPolicy: Parallel
    replicas: 3
    updateStrategy:
      type: RollingUpdate
    # revisionHistoryLimit: 3
    selector:
      matchLabels:
        app: zk
    serviceName: zk
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: zk
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - zk
                  topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: DoesNotExist
        containers:
        - image: quay.io/ypery/zookeeper:v0.7
          env:
          imagePullPolicy: Always
          name: zookeeper
          ports:
          - containerPort: 2181
            protocol: TCP
          - containerPort: 3888
            protocol: TCP
          - containerPort: 2888
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 300Mi
          livenessProbe:
            tcpSocket:
              port: 2181
            failureThreshold: 10
            initialDelaySeconds: 20
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /data
            name: zookeeper
          readinessProbe:
            exec:
              command:
              - /readiness.sh
            failureThreshold: 15
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        volumes:
          - emptyDir:
              medium: Memory
              sizeLimit: 200Mi
            name: zookeeper
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30


- apiVersion: v1
  kind: Service
  metadata:
    annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    labels:
      app: zk
    name: zksvc
  spec:
    ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
    selector:
      app: zk
    publishNotReadyAddresses: true

#zk headless service
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    labels:
      app: zk
    name: zk
  spec:
    ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: zookeeperelection
      port: 3888
      protocol: TCP
      targetPort: 3888
    - name: zookeeperelection2
      port: 2888
      protocol: TCP
      targetPort: 2888
    clusterIP: None
    selector:
      app: zk
    publishNotReadyAddresses: true

